In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

### Load the dataset

In [2]:
df = pd.read_csv('insurance.csv')

### Data Cleaning and preprocessing

In [3]:
df_cleaned = df.copy()

In [4]:
df_cleaned.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
df_cleaned.shape

(1338, 7)

## Remove Duplicate Records
Duplicate records can unnecessarily increase dataset size and processing time. Removing them also prevents repeated observations from having disproportionate influence during model training.

In [6]:
df_cleaned.drop_duplicates(inplace = True)

In [7]:
df_cleaned.shape

(1337, 7)

## Check for Missing Values
Check each feature for missing values because they may cause errors or unreliable results during model training. This helps determine whether imputation or another missing-value handling strategy is required.

In [8]:
df_cleaned.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [9]:
df_cleaned.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
charges     float64
dtype: object

In [10]:
df_cleaned['sex'].value_counts()

sex
male      675
female    662
Name: count, dtype: int64

### Encode Categorical Features
Inspect the unique values in the sex and smoker features and apply `Label Encoding` to convert their binary categories into numerical values. This preserves the categorical information in a model-compatible format.

In [11]:
df_cleaned['sex'] = df_cleaned['sex'].map({"male" : 0, "female" : 1})

In [12]:
df_cleaned.head()

   age  sex     bmi  children smoker     region      charges
0   19    1  27.900         0    yes  southwest  16884.92400
1   18    0  33.770         1     no  southeast   1725.55230
2   28    0  33.000         3     no  southeast   4449.46200
3   33    0  22.705         0     no  northwest  21984.47061
4   32    0  28.880         0     no  northwest   3866.85520

In [13]:
df_cleaned['smoker'].value_counts()

smoker
no     1063
yes     274
Name: count, dtype: int64

In [14]:
df_cleaned['smoker'] = df_cleaned['smoker'].map({"no" : 0, "yes" : 1})

In [15]:
df_cleaned.head()

   age  sex     bmi  children  smoker     region      charges
0   19    1  27.900         0       1  southwest  16884.92400
1   18    0  33.770         1       0  southeast   1725.55230
2   28    0  33.000         3       0  southeast   4449.46200
3   33    0  22.705         0       0  northwest  21984.47061
4   32    0  28.880         0       0  northwest   3866.85520

### Rename Encoded Features

In [16]:
df_cleaned.rename(columns={
    'sex' : 'is_female',
    'smoker': 'is_smoker'
                            }, inplace = True)

In [17]:
df_cleaned.head()

   age  is_female     bmi  children  is_smoker     region      charges
0   19          1  27.900         0          1  southwest  16884.92400
1   18          0  33.770         1          0  southeast   1725.55230
2   28          0  33.000         3          0  southeast   4449.46200
3   33          0  22.705         0          0  northwest  21984.47061
4   32          0  28.880         0          0  northwest   3866.85520

In [18]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

### One-Hot Encode region
Apply one-hot encoding because the regional categories have no natural numerical ordering. This represents each category independently without introducing an artificial relationship between regions.

In [19]:
df_cleaned = pd.get_dummies(df_cleaned, columns = ['region'])

In [20]:
df_cleaned.head()

,age,is_female,bmi,children,is_smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,16884.92400,False,False,False,True
1,18,0,33.770,1,0,1725.55230,False,False,True,False
2,28,0,33.000,3,0,4449.46200,False,False,True,False
3,33,0,22.705,0,0,21984.47061,False,True,False,False
4,32,0,28.880,0,0,3866.85520,False,True,False,False

### Convert Encoded Features to Integers
Convert Boolean indicator features into integer values represented by 0 and 1. This provides a consistent numerical representation for downstream preprocessing and model training.

In [21]:
df_cleaned = df_cleaned.astype(int)

In [22]:
df_cleaned

,age,is_female,bmi,children,is_smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,1,27,0,1,16884,0,0,0,1
1,18,0,33,1,0,1725,0,0,1,0
2,28,0,33,3,0,4449,0,0,1,0
3,33,0,22,0,0,21984,0,1,0,0
4,32,0,28,0,0,3866,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
1333,50,0,30,3,0,10600,0,1,0,0
1334,18,1,31,0,0,2205,1,0,0,0
1335,18,1,36,0,0,1629,0,0,1,0
1336,21,1,25,0,0,2007,0,0,0,1
1337,61,1,29,0,1,29141,0,1,0,0

In [23]:
df_cleaned.to_csv("cleaned_insurance.csv", index=False)